-- AlterTable
ALTER TABLE `apikeys` ADD COLUMN `dataPoints24h` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `lastIp` VARCHAR(191) NULL,
    ADD COLUMN `lastPath` VARCHAR(255) NULL,
    ADD COLUMN `lastUsedAt` DATETIME(3) NULL,
    ADD COLUMN `requestCount` INTEGER NOT NULL DEFAULT 0;
