export const allCategories = [
  'altador cup souvenir',
  'altadorian armour',
  'altadorian food',
  'altadorian magic',
  'altadorian petpets',
  'aquatic food',
  'aquatic petpet',
  'baked',
  'battle magic',
  'book',
  'booktastic book',
  'brightvale armour',
  'brightvale books',
  'brightvale fruit',
  'brightvale motes',
  'brightvale potions',
  'brightvale scroll',
  'brightvale windows',
  'broken toy',
  'candy',
  'clothes',
  'coffee',
  "cog's togs",
  'collectable card',
  'collectibles',
  'darigan toy',
  'defence magic',
  'desert food',
  'desert petpet',
  'desert pottery',
  'desert scroll',
  'desert weapon',
  'exotic foods',
  'faerie book',
  'faerie food',
  'faerie furniture',
  'faerie petpet',
  'faerie weapon shop',
  'fanciful fauna',
  'food',
  'furniture',
  'gardening',
  'geraptiku petpet',
  'gift',
  'grooming',
  'gross food',
  'haunted weaponry',
  'healing springs',
  'healthy food',
  'hot dog',
  'ice crystal',
  'instrument',
  'island merchandise',
  'jelly food',
  'kiko lake carpentry',
  'kiko lake food',
  'kreludan food',
  'kreludan furniture',
  "lampwyck's lights fantastic",
  'magic item',
  'maractite weaponry',
  'maraquan petpets',
  'medical cures',
  'medicine',
  'medieval food',
  'medieval petpet',
  'meridell potion',
  'moltaran books',
  'moltaran petpets',
  'molten morsels',
  'mystic mushroom',
  'mystical surroundings',
  'neohome',
  'neovian antiques',
  'neovian attire',
  'neovian pastries',
  'neovian press',
  'none',
  'petpet',
  'petpet supplies',
  'petpetpet',
  'pirate petpet',
  'pizza',
  'plushies',
  'qasalan food',
  'qasalan tablets',
  'qasalan weaponry',
  'refreshments',
  'remarkable restoratives',
  'robot petpet',
  'roo island merchandise',
  'school',
  'sea shells',
  'slushie',
  'smoothie',
  'snow food',
  'space battle',
  'space defence',
  'space food',
  'special',
  'spooky food',
  'spooky furniture',
  'spooky petpet',
  'springy things',
  'stamp',
  'toy',
  'trading card',
  'tropical food',
  'tyrannian food',
  'tyrannian furniture',
  'tyrannian petpet',
  'tyrannian weaponry',
  'ugga shinies',
  'usuki doll',
  'utility fish',
  'wintery petpet',
  'wonderous weaponry',
];
